import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UIProvider } from "@/context/ModalContext";
import { NotifModal } from "@/components/ui/Notif";

export const metadata: Metadata = {
	title: "Linktree",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`bg-gray-200 font-mono antialiased text-gray-900 relative`}>
				<UIProvider>
					{children}
					<NotifModal />
				</UIProvider>
			</body>
		</html>
	);
}
