import type { Metadata } from "next";
import Navbar from "@/components/dashboard/Nav";

export const metadata: Metadata = {
	title: "Linktree Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="p-5 relative w-screen h-screen ">
			<h1 className="text-3xl font-bold mb-5">Dashboard</h1>
			<Navbar />
			<div className="ml-24">{children}</div>
		</main>
	);
}
