import type { Metadata } from "next";
import { User, LinkIcon, Globe, View } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Linktree Profile",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="p-5 relative w-screen h-screen ">
			<h1 className="text-3xl font-bold mb-5">Dashboard</h1>
			<nav className="flex flex-col bg-gray-900 p-5 rounded-xl w-fit text-gray-200 gap-5 *:p-2 h-fit absolute  ">
				<Link href="/dashboard/profile" title="Profile Settings">
					<User />
				</Link>
				<Link href="/dashboard/social" title="Social Media Settings">
					<Globe />
				</Link>
				<Link href="/dashboard/link" title="Links Settings">
					<LinkIcon />
				</Link>
				<Link href="/" target="__blank" title="View Result">
					<View />
				</Link>
			</nav>
			<div className="ml-24">{children}</div>
		</main>
	);
}
